version: '3.8'
services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ../data/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ../data/redis/logs:/logs
    #配置文件启动
    command: redis-server /usr/local/etc/redis/redis.conf