version: '3.8'

services:
  mongodb:
    image: mongo:7.0.9
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ../data/mongo/mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
      MONGO_INITDB_DATABASE: yourdbname
